name: Build and Deploy Vertex AI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: devgm
      IMAGE_TAG: ${{ github.sha }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install kfp google-cloud-aiplatform

    - name: Authenticate with GCP
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          gcr.io/vertex-demo-1-385406/my-image
          gcr.io/vertex-demo-1-385406/my-image:latest
      env:
        DOCKER_BUILDKIT: 1

    - name: Deploy pipeline to Vertex AI
      run: |
        aiplatform pipeline create \
          --display-name=my-pipeline \
          --description="My Vertex AI pipeline" \
          --container-image-uri=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-artifact-registry/my-image:${{ github.sha }} \
          --machine-type=n1-standard-4 \
          --service-account=vai-dev@vertex-demo-1-385406.iam.gserviceaccount.com \
          --input-paths=training_data_uri:string,serving_container_image_uri:string \
          --output-paths=model:artifact,endpoint:artifact
      env:
        GOOGLE_CLOUD_PROJECT: ${{ secrets.GCP_PROJECT_ID }}

    - name: Clean up
      run: |
        docker rmi gcr.io/$PROJECT_ID/my-image:${IMAGE_TAG}
