name: Deploy Vertex AI Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install kfp google-cloud-aiplatform

    - name: Compile pipeline
      run: |
        python pipeline.py

    - name: Authenticate with GCP
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@main
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy pipeline
      run: |
        gcloud auth configure-docker
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/basic-vertex-ai-pipeline .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/basic-vertex-ai-pipeline
        aiplatform pipeline create \
          --display-name=basic-vertex-ai-pipeline \
          --description="My Vertex AI pipeline" \
          --docker-image-uri=gcr.io/${{ secrets.GCP_PROJECT_ID }}/basic-vertex-ai-pipeline \
          --machine-type=n1-standard-4 \
          --service-account=$GOOGLE_CLOUD_PROJECT@appspot.gserviceaccount.com \
          --input-paths=training_data_uri:string,serving_container_image_uri:string \
          --output-paths=model:artifact,endpoint:artifact

    - name: Clean up
      run: |
        docker rmi gcr.io/${{ secrets.GCP_PROJECT_ID }}/basic-vertex-ai-pipeline
