name: Build and Deploy Vertex AI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: vertex-demo-1-385406
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Authenticate with GCP
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker with gcloud credentials
        run: |
          gcloud auth configure-docker
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

      - name: Grant Artifact Registry permission
        run: |
          gcloud artifacts repositories add-iam-policy-binding my-artifact-registry \
            --location=us-central1 \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --member=serviceAccount:${{ secrets.GCP_SA_EMAIL }} \
            --role=roles/artifactregistry.writer
        env:
          GCP_SA_EMAIL: ${{ secrets.GCP_SA_EMAIL }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-artifact-registry/my-image:${{ github.sha }}
            us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-artifact-registry/my-image:latest
        env:
          DOCKER_BUILDKIT: 1
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy pipeline to Vertex AI
        run: |
          aiplatform pipeline create \
            --display-name=my-pipeline \
            --description="My Vertex AI pipeline" \
            --container-image-uri=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-artifact-registry/my-image:${{ github.sha }} \
            --machine-type=n1-standard-4 \
            --service-account=vai-dev@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com \
            --input-paths=training_data_uri:string,serving_container_image_uri:string \
            --output-paths=model:artifact,endpoint:artifact
        env:
          GOOGLE_CLOUD_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

      - name: Clean up
        run: |
          docker rmi us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-artifact-registry/my-image:${{ github.sha }}
